runtime: nodejs8
env: standard

automatic_scaling:
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_instances: 1
  min_instances: 1

handlers:
- url: /.*
  script: true
  secure: always
  redirect_http_response_code: 301